//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDB_LSMLL8                      8
#define IDB_LSMALL8                     8
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_MAP0                        157
#define IDB_MAP1                        158
#define IDB_HERORIGHT                   159
#define IDB_HEROLEFT                    160
#define IDB_RHERORUN2                   166
#define IDB_RHERORUN3                   167
#define IDB_RHERORUN4                   168
#define IDB_RHERORUN5                   169
#define IDB_RHERORUN6                   170
#define IDB_RHERORUN7                   171
#define IDB_RHERORUN8                   172
#define IDB_RHERORUN9                   173
#define IDB_RHERORUN10                  174
#define IDB_RHERORUN11                  175
#define IDB_RHERORUN1                   176
#define IDB_RSTAY1                      177
#define IDB_RSTAY2                      178
#define IDB_RSTAY3                      179
#define IDB_RSTAY4                      180
#define IDB_RSTAY5                      181
#define IDB_RSTAY6                      182
#define IDB_RSTAY7                      183
#define IDB_RSTAY8                      184
#define IDB_RSTAY9                      185
#define IDB_RSTAY10                     186
#define IDB_RSTAY11                     187
#define IDB_RFOOT                       196
#define IDB_RAttache1                   212
#define IDB_RAttache2                   213
#define IDB_RAttache3                   214
#define IDB_RAttache4                   215
#define IDB_RAttache5                   216
#define IDB_RAttache6                   217
#define IDB_RAttache7                   218
#define IDB_RAttache8                   219
#define IDB_RAttache9                   220
#define IDB_RSTAY12                     221
#define IDB_RSTAY13                     222
#define IDB_RSTAY14                     223
#define IDB_RSTAY15                     224
#define IDB_RSTAY16                     225
#define IDB_RSTAY17                     226
#define IDB_RSTAY18                     227
#define IDB_RSTAY19                     228
#define IDB_LFOOT                       229
#define IDB_LSTAY1                      230
#define IDB_LSTAY2                      231
#define IDB_LSTAY3                      232
#define IDB_LSTAY4                      233
#define IDB_LSTAY5                      234
#define IDB_LSTAY6                      235
#define IDB_LSTAY7                      236
#define IDB_LSTAY8                      237
#define IDB_LSTAY9                      238
#define IDB_LSTAY10                     239
#define IDB_LSTAY11                     240
#define IDB_LSTAY12                     241
#define IDB_LSTAY13                     242
#define IDB_LSTAY14                     243
#define IDB_LSTAY15                     244
#define IDB_LSTAY16                     245
#define IDB_LSTAY17                     246
#define IDB_LSTAY18                     247
#define IDB_LSTAY19                     248
#define IDB_LHERORUN1                   249
#define IDB_LHERORUN2                   250
#define IDB_LHERORUN3                   251
#define IDB_LHERORUN4                   252
#define IDB_LHERORUN5                   253
#define IDB_LHERORUN6                   254
#define IDB_LHERORUN8                   256
#define IDB_LHERORUN9                   257
#define IDB_LHERORUN10                  258
#define IDB_LHERORUN11                  259
#define IDB_LHERORUN7                   260
#define IDB_LAttache1                   264
#define IDB_LAttache2                   265
#define IDB_LAttache3                   266
#define IDB_LAttache4                   267
#define IDB_LAttache5                   268
#define IDB_LAttache6                   269
#define IDB_LAttache7                   270
#define IDB_LAttache8                   271
#define IDB_BITMAP11                    272
#define IDB_LAttache9                   272
#define IDB_RSMALL1                     273
#define IDB_RSMALL2                     274
#define IDB_RSMALL3                     275
#define IDB_RSMALL4                     276
#define IDB_RSMALL5                     277
#define IDB_RSMALL6                     278
#define IDB_RSMALL7                     279
#define IDB_RSMALL8                     280
#define IDB_RSMALL9                     281
#define IDB_RSMALL10                    282
#define IDB_LSMALL1                     283
#define IDB_LSMALL2                     284
#define IDB_LSMALL3                     285
#define IDB_LSMALL4                     286
#define IDB_LSMALL5                     287
#define IDB_LSMALL6                     288
#define IDB_LSMALL7                     289
#define IDB_LSMALL9                     291
#define IDB_LSMALL10                    292
#define IDB_AVATER                      293
#define IDB_AVATAR                      293
#define IDB_BITMAP3                     294
#define IDB_ATTACKAAR1                  294
#define IDB_BITMAP4                     295
#define IDB_BITMAP5                     296
#define IDB_BITMAP6                     297
#define IDB_BITMAP7                     298
#define IDB_BITMAP8                     299
#define IDB_BITMAP9                     300
#define IDB_ATTACKAAR7                  301
#define IDB_ATTACKAAR6                  302
#define IDB_ATTACKAAR5                  303
#define IDB_ATTACKAAR4                  304
#define IDB_ATTACKAAR3                  305
#define IDB_ATTACKAAR2                  306
#define IDB_BITMAP10                    307
#define IDB_BITMAP12                    308
#define IDB_BITMAP13                    309
#define IDB_BITMAP14                    310
#define IDB_BITMAP15                    311
#define IDB_BITMAP16                    312
#define IDB_BITMAP17                    313
#define IDB_ATTACKAAL1                  314
#define IDB_ATTACKAAL2                  315
#define IDB_ATTACKAAL3                  316
#define IDB_ATTACKAAL4                  317
#define IDB_ATTACKAAL5                  318
#define IDB_ATTACKAAL6                  319
#define IDB_ATTACKAAL7                  320
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        324
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
